apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nxrm-operator-certified
spec:
  channel: stable
  installPlanApproval: Automatic
  name: nxrm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
