- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ ocp_cluster_token | default(omit) }}"
    common_k8s_host: "{{ ocp_api_endpoint | default(omit) }}"
    common_namespace_name: apollo-one-shot
    common_output_directory: "{{ generic_directory }}"

- name: Get OCP Apps domain
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ ocp_cluster_token | default(omit) }}"
    common_k8s_host: "{{ ocp_api_endpoint | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"

- name: Get git repo revision
  ansible.builtin.git: 
    repo: .
    dest: .
    update: no
    clone: no
  register: git_repo_information

- name: Git commit id 
  ansible.builtin.set_fact: 
    git_commit_id: "{{ git_repo_information.before  if git_repo_information.before else git_repo_information.after }}"

- name: Generate usage
  ansible.builtin.include_role:
    name: usage

- name: Install Global CA
  ansible.builtin.include_role:
    name: global_ca

- name: Install DB2
  ansible.builtin.include_role:
    name: db2

- name: Install DB2MC
  ansible.builtin.include_role:
    name: db2mc
  when: db2mc_enabled

- name: Install PostgreSQL
  ansible.builtin.include_role:
    name: postgresql

- name: Install pgAdmin
  ansible.builtin.include_role:
    name: pgadmin
  when: pgadmin_enabled

- name: Install openldap
  ansible.builtin.include_role:
    name: openldap
  when: openldap_enabled

- name: Install gitea
  ansible.builtin.include_role:
    name: gitea
  when: gitea_enabled

- name: Install nexus
  ansible.builtin.include_role:
    name: nexus

- name: Install Mail
  ansible.builtin.include_role:
    name: mail
  when: mail_enabled

- name: Install Roundcube
  ansible.builtin.include_role:
    name: roundcube
  when: roundcube_enabled

- name: Install Cerebro
  ansible.builtin.include_role:
    name: cerebro
  when: cerebro_enabled

- name: Install AKHQ
  ansible.builtin.include_role:
    name: akhq
  when: akhq_enabled

- name: Install Kibana
  ansible.builtin.include_role:
    name: kibana
  when: kibana_enabled

- name: Install MongoDB
  ansible.builtin.include_role:
    name: mongodb
  when: mongodb_enabled

- name: Install Mongo Express
  ansible.builtin.include_role:
    name: mongo_express
  when: mongo_express_enabled

- name: Install CPFS
  ansible.builtin.include_role:
    name: cpfs

- name: Install CP4BA
  ansible.builtin.include_role:
    name: cp4ba

# TODO requires some CP4I resources and fails
#- name: Install Asset Repo
#  ansible.builtin.include_role:
#    name: asset_repo
#  when: asset_repo_enabled

- name: RPA group
  block:

    - name: Install MSSQL
      ansible.builtin.include_role:
        name: mssql

    - name: Install RPA
      ansible.builtin.include_role:
        name: rpa

  when: rpa_enabled

- name: Install PM
  ansible.builtin.include_role:
    name: pm
  when: pm_enabled

# TODO activate when fixed if still needed
# - name: Assign Asset Repo Roles
#   ansible.builtin.include_role:
#     name: asset_repo
#     tasks_from: assign-roles
#   when: asset_repo_enabled
