- name: Remove PM
  ansible.builtin.include_role:
    name: pm
  when: pm_enabled
  
- name: RPA group
  block:

    - name: Remove RPA
      ansible.builtin.include_role:
        name: rpa

    - name: Remove cloudbeaver
      ansible.builtin.include_role:
        name: cloudbeaver
      when: cloudbeaver_enabled

    - name: Remove MSSQL
      ansible.builtin.include_role:
        name: mssql

  when: rpa_enabled

# TODO requires some CP4I resources and fails
# - name: Remove Asset Repo
#   ansible.builtin.include_role:
#     name: asset_repo
#   when: asset_repo_enabled

- name: Remove CP4BA
  ansible.builtin.include_role:
    name: cp4ba

- name: Remove CPFS
  ansible.builtin.include_role:
    name: cpfs

- name: Remove Mongo Express
  ansible.builtin.include_role:
    name: mongo_express
  when: mongo_express_enabled

- name: Remove MongoDB
  ansible.builtin.include_role:
    name: mongodb
  when: mongodb_enabled    

- name: Remove Kibana
  ansible.builtin.include_role:
    name: kibana
  when: kibana_enabled    

- name: Remove AKHQ
  ansible.builtin.include_role:
    name: akhq
  when: akhq_enabled

- name: Remove Cerebro
  ansible.builtin.include_role:
    name: cerebro
  when: cerebro_enabled

- name: Remove Roundcube
  ansible.builtin.include_role:
    name: roundcube
  when: roundcube_enabled

- name: Remove Mail
  ansible.builtin.include_role:
    name: mail
  when: mail_enabled    

- name: Remove nexus
  ansible.builtin.include_role:
    name: nexus

- name: Remove gitea
  ansible.builtin.include_role:
    name: gitea
  when: gitea_enabled    

- name: Remove openldap
  ansible.builtin.include_role:
    name: openldap
  when: openldap_enabled

- name: Remove pgAdmin
  ansible.builtin.include_role:
    name: pgadmin
  when: pgadmin_enabled

- name: Remove PostgreSQL
  ansible.builtin.include_role:
    name: postgresql

- name: Remove DB2MC
  ansible.builtin.include_role:
    name: db2mc
  when: (cp4ba_config.deployment_patterns.document_processing or pm_enabled) and db2mc_enabled

- name: Remove DB2
  ansible.builtin.include_role:
    name: db2
  when: cp4ba_config.deployment_patterns.document_processing or pm_enabled

- name: Remove usage
  ansible.builtin.include_role:
    name: usage

- name: Remove Global CA
  ansible.builtin.include_role:
    name: global_ca
